#!/bin/bash

if [ $# -lt 1 ]; then
  cat <<EOM
  usage: $0: $0 <branch-name> [remote-name]

EOM
exit 0
fi

BRANCH_NAME=$1
REMOTE_NAME=${2:-origin}

git checkout -b "$BRANCH_NAME"
git push -u "$REMOTE_NAME" "$BRANCH_NAME"

